# Generated by Django 5.2.9 on 2026-01-06 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaces_pedagogiques', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('espaces', models.ManyToManyField(blank=True, related_name='etudiants', to='espaces_pedagogiques.espacepedagogique', verbose_name='Espaces pédagogiques')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='TravailIndividuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_echeance', models.DateTimeField(verbose_name="Date d'échéance")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('espace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travaux_individuels', to='espaces_pedagogiques.espacepedagogique', verbose_name='Espace pédagogique')),
            ],
            options={
                'verbose_name': 'Travail Individuel',
                'verbose_name_plural': 'Travaux Individuels',
                'ordering': ['-date_echeance'],
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Contenu de la livraison')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='livraisons/', verbose_name='Fichier joint')),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='espaces_pedagogiques.etudiant', verbose_name='Étudiant')),
                ('travail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='espaces_pedagogiques.travailindividuel', verbose_name='Travail Individuel')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'ordering': ['-date_soumission'],
                'unique_together': {('etudiant', 'travail')},
            },
        ),
    ]
