# Generated by Django 5.2.9 on 2026-01-06 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espaces_pedagogiques', '0002_etudiant_travailindividuel_livraison'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='espacepedagogique',
            options={'ordering': ['nom', 'matiere'], 'verbose_name': 'Espace pédagogique', 'verbose_name_plural': 'Espaces pédagogiques'},
        ),
        migrations.AddField(
            model_name='espacepedagogique',
            name='nom',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name="Nom de l'espace"),
        ),
    ]
